# Generated by Django 2.2.16 on 2022-03-19 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220319_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Оценка должна быть больше 1!'), django.core.validators.MaxValueValidator(10, 'Оценка должна быть меньше 10!')]),
        ),
    ]
